### ISSUE TITLE
Reporte de Practica 2 Interfaz Grafica

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/practica-de-visual-studio-Abraham890#3]
[Abraham_Reyes_Ortiz_Reporte._De_Interfaz_Grafica_4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-Abraham890/files/6166825/Abraham_Reyes_Ortiz_Reporte._De_Interfaz_Grafica_4US.pdf)

**Comment by Eva155** [comment]
Desde mi criterio cumple con todos los puntos que marca la rúbrica es por ello que le asigno la siguiente:
Calificación: 100/100
Calificó: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado...
